/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param etiqueta 
 * @param numeroSerie 
 * @param idTipoActivo 
 * @param idModelo 
 * @param idEspacio 
 * @param id 
 * @param estadoCustodia 
 * @param estadoOperativo 
 * @param descripcion 
 * @param costo 
 * @param qrCodigo 
 * @param fechaAlta 
 * @param esActivo 
 */


data class AssetsDTO (

    @Json(name = "etiqueta")
    val etiqueta: kotlin.String,

    @Json(name = "numeroSerie")
    val numeroSerie: kotlin.String,

    @Json(name = "idTipoActivo")
    val idTipoActivo: kotlin.Long,

    @Json(name = "idModelo")
    val idModelo: kotlin.Long,

    @Json(name = "idEspacio")
    val idEspacio: kotlin.Long,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "estadoCustodia")
    val estadoCustodia: kotlin.String? = null,

    @Json(name = "estadoOperativo")
    val estadoOperativo: kotlin.String? = null,

    @Json(name = "descripcion")
    val descripcion: kotlin.String? = null,

    @Json(name = "costo")
    val costo: java.math.BigDecimal? = null,

    @Json(name = "qrCodigo")
    val qrCodigo: kotlin.String? = null,

    @Json(name = "fechaAlta")
    val fechaAlta: kotlin.String? = null,

    @Json(name = "esActivo")
    val esActivo: kotlin.Boolean? = null

) {


}

