/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param idActivo 
 * @param idUsuario 
 * @param tipoEvento 
 * @param descripcion 
 * @param id 
 * @param estadoCustodiaAnterior 
 * @param estadoCustodiaNuevo 
 * @param estadoOperativoAnterior 
 * @param estadoOperativoNuevo 
 */


data class BitacoraDTO (

    @Json(name = "idActivo")
    val idActivo: kotlin.Long,

    @Json(name = "idUsuario")
    val idUsuario: kotlin.Long,

    @Json(name = "tipoEvento")
    val tipoEvento: kotlin.String,

    @Json(name = "descripcion")
    val descripcion: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "estadoCustodiaAnterior")
    val estadoCustodiaAnterior: kotlin.String? = null,

    @Json(name = "estadoCustodiaNuevo")
    val estadoCustodiaNuevo: kotlin.String? = null,

    @Json(name = "estadoOperativoAnterior")
    val estadoOperativoAnterior: kotlin.String? = null,

    @Json(name = "estadoOperativoNuevo")
    val estadoOperativoNuevo: kotlin.String? = null

) {


}

