/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param passwordNueva 
 * @param token 
 * @param correo 
 * @param passwordActual 
 */


data class ChangePasswordDTO (

    @Json(name = "passwordNueva")
    val passwordNueva: kotlin.String,

    @Json(name = "token")
    val token: kotlin.String? = null,

    @Json(name = "correo")
    val correo: kotlin.String? = null,

    @Json(name = "passwordActual")
    val passwordActual: kotlin.String? = null

) {


}

