/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param idEdificio 
 * @param nombreEspacio 
 * @param id 
 * @param tipoEspacio 
 * @param descripcion 
 * @param esActivo 
 */


data class EspacioDTO (

    @Json(name = "idEdificio")
    val idEdificio: kotlin.Long,

    @Json(name = "nombreEspacio")
    val nombreEspacio: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "tipoEspacio")
    val tipoEspacio: kotlin.String? = null,

    @Json(name = "descripcion")
    val descripcion: kotlin.String? = null,

    @Json(name = "esActivo")
    val esActivo: kotlin.Boolean? = null

) {


}

