/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param idReporte 
 * @param idActivo 
 * @param idUsuarioTecnico 
 * @param idUsuarioAdmin 
 * @param idPrioridad 
 * @param tipoAsignado 
 * @param id 
 * @param tipoEjecutado 
 * @param diagnostico 
 * @param accionesRealizadas 
 * @param piezasUtilizadas 
 * @param conclusion 
 * @param observaciones 
 * @param costo 
 * @param estadoMantenimiento 
 */


data class MantenimientoDTO (

    @Json(name = "idReporte")
    val idReporte: kotlin.Long,

    @Json(name = "idActivo")
    val idActivo: kotlin.Long,

    @Json(name = "idUsuarioTecnico")
    val idUsuarioTecnico: kotlin.Long,

    @Json(name = "idUsuarioAdmin")
    val idUsuarioAdmin: kotlin.Long,

    @Json(name = "idPrioridad")
    val idPrioridad: kotlin.Long,

    @Json(name = "tipoAsignado")
    val tipoAsignado: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "tipoEjecutado")
    val tipoEjecutado: kotlin.String? = null,

    @Json(name = "diagnostico")
    val diagnostico: kotlin.String? = null,

    @Json(name = "accionesRealizadas")
    val accionesRealizadas: kotlin.String? = null,

    @Json(name = "piezasUtilizadas")
    val piezasUtilizadas: kotlin.String? = null,

    @Json(name = "conclusion")
    val conclusion: kotlin.String? = null,

    @Json(name = "observaciones")
    val observaciones: kotlin.String? = null,

    @Json(name = "costo")
    val costo: java.math.BigDecimal? = null,

    @Json(name = "estadoMantenimiento")
    val estadoMantenimiento: kotlin.String? = null

) {


}

