/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param idMarca 
 * @param nombre 
 * @param id 
 */


data class ModeloDTO (

    @Json(name = "idMarca")
    val idMarca: kotlin.Long,

    @Json(name = "nombre")
    val nombre: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long? = null

) {


}

