/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param nivel 
 * @param id 
 * @param tiempoRespuestaHoras 
 */


data class PrioridadDTO (

    @Json(name = "nivel")
    val nivel: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "tiempoRespuestaHoras")
    val tiempoRespuestaHoras: kotlin.Int? = null

) {


}

