/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param nombreCompleto 
 * @param correo 
 * @param fechaNacimiento 
 * @param curp 
 * @param idRol 
 * @param idArea 
 */


data class RegisterDTO (

    @Json(name = "nombreCompleto")
    val nombreCompleto: kotlin.String,

    @Json(name = "correo")
    val correo: kotlin.String,

    @Json(name = "fechaNacimiento")
    val fechaNacimiento: kotlin.String,

    @Json(name = "curp")
    val curp: kotlin.String,

    @Json(name = "idRol")
    val idRol: kotlin.Long,

    @Json(name = "idArea")
    val idArea: kotlin.Long

) {


}

