/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param idActivo 
 * @param idUsuarioReporta 
 * @param idTipoFalla 
 * @param idPrioridad 
 * @param descripcionFalla 
 * @param id 
 * @param estadoReporte 
 */


data class ReporteDTO (

    @Json(name = "idActivo")
    val idActivo: kotlin.Long,

    @Json(name = "idUsuarioReporta")
    val idUsuarioReporta: kotlin.Long,

    @Json(name = "idTipoFalla")
    val idTipoFalla: kotlin.Long,

    @Json(name = "idPrioridad")
    val idPrioridad: kotlin.Long,

    @Json(name = "descripcionFalla")
    val descripcionFalla: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "estadoReporte")
    val estadoReporte: kotlin.String? = null

) {


}

