/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param idActivo 
 * @param idUsuarioEmpleado 
 * @param idUsuarioAdmin 
 * @param id 
 * @param observacionesAsig 
 * @param observacionesConf 
 * @param observacionesDev 
 * @param estadoResguardo 
 */


data class ResguardoDTO (

    @Json(name = "idActivo")
    val idActivo: kotlin.Long,

    @Json(name = "idUsuarioEmpleado")
    val idUsuarioEmpleado: kotlin.Long,

    @Json(name = "idUsuarioAdmin")
    val idUsuarioAdmin: kotlin.Long,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "observacionesAsig")
    val observacionesAsig: kotlin.String? = null,

    @Json(name = "observacionesConf")
    val observacionesConf: kotlin.String? = null,

    @Json(name = "observacionesDev")
    val observacionesDev: kotlin.String? = null,

    @Json(name = "estadoResguardo")
    val estadoResguardo: kotlin.String? = null

) {


}

