/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param idActivo 
 * @param idMantenimiento 
 * @param id 
 * @param idUsuarioAdmin 
 * @param estado 
 * @param justificacion 
 * @param observacionesAdmin 
 */


data class SolicitudBajaDTO (

    @Json(name = "idActivo")
    val idActivo: kotlin.Long,

    @Json(name = "idMantenimiento")
    val idMantenimiento: kotlin.Long,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "idUsuarioAdmin")
    val idUsuarioAdmin: kotlin.Long? = null,

    @Json(name = "estado")
    val estado: kotlin.String? = null,

    @Json(name = "justificacion")
    val justificacion: kotlin.String? = null,

    @Json(name = "observacionesAdmin")
    val observacionesAdmin: kotlin.String? = null

) {


}

