/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param nombre 
 * @param tipoBien 
 * @param id 
 * @param descripcion 
 * @param esActivo 
 */


data class TipoActivoDTO (

    @Json(name = "nombre")
    val nombre: kotlin.String,

    @Json(name = "tipoBien")
    val tipoBien: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "descripcion")
    val descripcion: kotlin.String? = null,

    @Json(name = "esActivo")
    val esActivo: kotlin.Boolean? = null

) {


}

