/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.activos360.back.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param nombreCompleto 
 * @param correo 
 * @param curp 
 * @param fechaNacimiento 
 * @param idRol 
 * @param idArea 
 * @param id 
 * @param numeroEmpleado 
 * @param password 
 * @param primerLogin 
 * @param esActivo 
 */


data class UserDTO (

    @Json(name = "nombreCompleto")
    val nombreCompleto: kotlin.String,

    @Json(name = "correo")
    val correo: kotlin.String,

    @Json(name = "curp")
    val curp: kotlin.String,

    @Json(name = "fechaNacimiento")
    val fechaNacimiento: kotlin.String,

    @Json(name = "idRol")
    val idRol: kotlin.Long,

    @Json(name = "idArea")
    val idArea: kotlin.Long,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "numeroEmpleado")
    val numeroEmpleado: kotlin.String? = null,

    @Json(name = "password")
    val password: kotlin.String? = null,

    @Json(name = "primerLogin")
    val primerLogin: kotlin.Boolean? = null,

    @Json(name = "esActivo")
    val esActivo: kotlin.Boolean? = null

) {


}

